# Generated by Django 5.2 on 2025-04-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_app_settings_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_settings',
            name='value',
            field=models.JSONField(max_length=255),
        ),
    ]
