# Generated by Django 5.2 on 2025-04-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('last_visit', models.TextField()),
                ('title', models.TextField()),
                ('visit_count', models.IntegerField()),
                ('category', models.TextField()),
                ('browser', models.TextField()),
            ],
        ),
    ]
