# Generated by Django 5.2 on 2025-04-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_settings',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
